name: Greg Arnold
favicon: null
layout_spectrum: 0.9960578470490873
typography_spectrum: 0.9103616166394204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.019397061318159103
  lightness: 0.5933643791358918
  saturation: 0.8497808601241559
  rhythmicContrast: 0.27931801276281476
purpose: []
